export const START_SEARCH = 'START_SEARCH'

export const END_CATEGORY_SEARCH = 'END_CATEGORY_SEARCH'
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY'

export const END_VENUE_SEARCH = 'END_VENUE_SEARCH'
export const SELECTED_VENUE = 'SELECTED_VENUE'

export const START_WEATHER_SEARCH = 'START_WEATHER_SEARCH'
export const END_WEATHER_SEARCH = 'END_WEATHER_SEARCH'
export const SELECTED_WEATHER = 'SELECTED_WEATHER'

export const ADD_MAP_MARKER = 'ADD_MAP_MARKER'
export const SET_MAP_CENTER = 'SET_MAP_CENTER'
export const SELECTED_MARKER = 'SELECTED_MARKER'
