export const START_SEARCH = 'START_SEARCH'
export const END_SEARCH = 'END_SEARCH'
export const SELECTED_VENUE = 'SELECTED_VENUE'

export const ADD_MAP_MARKER = 'ADD_MAP_MARKER'
export const SET_MAP_CENTER = 'SET_MAP_CENTER'
export const SELECTED_MARKER = 'SELECTED_MARKER'

export const DISABLE_MARKER_CLICK = 'DISABLE_MARKER_CLICK'
